import { db } from "./firebase-config.js";

import {
  collection,
  getDocs
} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

async function loadAnalytics(){

  const querySnapshot = await getDocs(
    collection(db, "tasks")
  );

  const subjects = {};
  let low = 0;
  let moderate = 0;
  let high = 0;

  querySnapshot.forEach((doc) => {

    const task = doc.data();

    if(subjects[task.subject]){
      subjects[task.subject] += task.workloadScore;
    }
    else{
      subjects[task.subject] = task.workloadScore;
    }

    if(task.workloadScore <= 2){
      low++;
    }
    else if(task.workloadScore <= 4){
      moderate++;
    }
    else{
      high++;
    }

  });

  createSubjectChart(subjects);

  createPieChart(low, moderate, high);

}

function createSubjectChart(subjects){

  const ctx =
    document.getElementById("subjectChart");

  new Chart(ctx, {

    type: "bar",

    data: {
      labels: Object.keys(subjects),

      datasets: [{
        label: "Subject Workload",
        data: Object.values(subjects),
        borderWidth: 2
      }]
    }

  });

}

function createPieChart(low, moderate, high){

  const ctx =
    document.getElementById("workloadPieChart");

  new Chart(ctx, {

    type: "pie",

    data: {
      labels: [
        "Low",
        "Moderate",
        "High"
      ],

      datasets: [{
        data: [low, moderate, high]
      }]
    }

  });

}

document
  .getElementById("exportBtn")
  .addEventListener("click", exportPDF);

function exportPDF(){

  const { jsPDF } = window.jspdf;

  const doc = new jsPDF();

  doc.setFontSize(18);

  doc.text(
    "Academic Load Analytics Report",
    20,
    20
  );

  doc.setFontSize(12);

  doc.text(
    "Generated by Academic Energy and Load Balancing System",
    20,
    35
  );

  doc.text(
    "This report summarizes workload analytics and pressure monitoring data.",
    20,
    50
  );

  doc.save("Academic_Report.pdf");

}

loadAnalytics();
